#!/usr/bin/env python3
"""Vis Arena participant agent — protocol entrypoint.

This file IS the arena contract. The worker invokes:

    ./agent.py info     --output agent-info.json
    ./agent.py generate --task task.md --data-dir data --output-dir output
    ./agent.py evaluate --task task.md --data-dir data \\
                        --source-dir output/source --dist-dir output/dist \\
                        --output evaluation.json

It dispatches to three hook functions in example_agent.py:

    info()                                              -> dict (agent metadata)
    generate(task_path, data_dir, source_dir, dist_dir) -> dict (notes only)
    evaluate(task_path, data_dir, source_dir, dist_dir) -> dict (score + criteria)

Plug in your own agent by replacing example_agent.py — keep these three function
names and signatures and the arena contract keeps working. You usually do NOT
need to edit this file.
"""
from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import example_agent


def main() -> None:
    parser = argparse.ArgumentParser(description="Vis Arena agent contract")
    sub = parser.add_subparsers(dest="command", required=True)

    info = sub.add_parser("info")
    info.add_argument("--output", required=True)

    models = sub.add_parser("models")
    models.add_argument("--output")

    gen = sub.add_parser("generate")
    gen.add_argument("--task", required=True)
    gen.add_argument("--data-dir", required=True)
    gen.add_argument("--output-dir", required=True)

    ev = sub.add_parser("evaluate")
    ev.add_argument("--task", required=True)
    ev.add_argument("--data-dir", required=True)
    ev.add_argument("--source-dir", required=True)
    ev.add_argument("--dist-dir", required=True)
    ev.add_argument("--output", required=True)

    args = parser.parse_args()
    if args.command == "info":
        _write_json(Path(args.output), {"schema_version": "vis-arena.agent.v1", **example_agent.info()})
    elif args.command == "models":
        payload = example_agent.models()
        if args.output:
            _write_json(Path(args.output), payload)
        else:
            print(json.dumps(payload, indent=2))
    elif args.command == "generate":
        _run_generate(args)
    elif args.command == "evaluate":
        _run_evaluate(args)


def _run_generate(args: argparse.Namespace) -> None:
    task_path = Path(args.task).resolve()
    data_dir = Path(args.data_dir).resolve()
    output_dir = Path(args.output_dir).resolve()
    source_dir = output_dir / "source"
    dist_dir = output_dir / "dist"
    source_dir.mkdir(parents=True, exist_ok=True)
    dist_dir.mkdir(parents=True, exist_ok=True)

    result = example_agent.generate(task_path, data_dir, source_dir, dist_dir) or {}
    if not (dist_dir / "index.html").exists():
        raise SystemExit("Generation failed: dist/index.html was not created")

    task_text = task_path.read_text(encoding="utf-8")
    _write_json(output_dir / "generation.json", {
        "schema_version": "vis-arena.generation.v1",
        "task_id": _extract_task_id(task_text),
        "entrypoint": "index.html",
        "source_dir": "source",
        "dist_dir": "dist",
        "created_at": _now(),
        "notes": result.get("notes") or result.get("summary") or "Generated by template agent.",
    })


def _run_evaluate(args: argparse.Namespace) -> None:
    task_path = Path(args.task).resolve()
    data_dir = Path(args.data_dir).resolve()
    source_dir = Path(args.source_dir).resolve()
    dist_dir = Path(args.dist_dir).resolve()
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    result = example_agent.evaluate(task_path, data_dir, source_dir, dist_dir) or {}
    task_id = _extract_task_id(task_path.read_text(encoding="utf-8"))
    score = float(result.get("score", 0))
    max_score = float(result.get("max_score", 100))
    _write_json(output_path, {
        "schema_version": "vis-arena.evaluation.v1",
        "task_id": task_id,
        "score": max(0.0, min(score, max_score)),
        "max_score": max_score,
        "summary": str(result.get("summary", "")),
        "criteria": result.get("criteria", []),
        "browser": result.get("browser", {}),
        "source_observations": result.get("source_observations", []),
        "artifacts": result.get("artifacts", {}),
        "metadata": (result.get("metadata") or {}) | {"evaluated_at": _now()},
    })


def _extract_task_id(task_text: str) -> str:
    if task_text.startswith("---"):
        header = task_text.split("---", 2)[1]
        for line in header.splitlines():
            if line.startswith("id:"):
                return line.split(":", 1)[1].strip()
    return "unknown-task"


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _now() -> str:
    return datetime.now(UTC).isoformat()


if __name__ == "__main__":
    main()
