#!/usr/bin/env python3
"""Vis Arena participant agent — protocol entrypoint.

This file IS the arena contract. The worker invokes:

    ./agent.py info     --output agent-info.json
    ./agent.py generate <workdir>
    ./agent.py evaluate <workdir>

It dispatches to hooks in example_agent.py:

    info()                                 -> dict (agent metadata)
    models()                               -> dict (optional, for debugging)
    generate(workdir)                      -> dict (slim notes)
    evaluate(workdir, artifact_url)        -> dict (the evaluation report)

The workdir holds task input AND agent output at fixed paths (see agent.md).
For evaluate, this file also runs a localhost HTTP server pointing at
workdir/dist/ and passes the URL to your hook so Playwright behaves the same
way it will against the arena's preview endpoint later.

Plug in your own agent by replacing example_agent.py — keep these function
names and signatures and the arena contract keeps working. You usually do NOT
need to edit this file.
"""
from __future__ import annotations

import argparse
import http.server
import json
import socketserver
import threading
from contextlib import contextmanager
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterator

import example_agent


# ---------------------------------------------------------------------------
# CLI dispatch
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Vis Arena agent contract")
    sub = parser.add_subparsers(dest="command", required=True)

    info = sub.add_parser("info")
    info.add_argument("--output", required=True)

    models = sub.add_parser("models")
    models.add_argument("--output")

    gen = sub.add_parser("generate")
    gen.add_argument("workdir")

    ev = sub.add_parser("evaluate")
    ev.add_argument("workdir")

    args = parser.parse_args()
    if args.command == "info":
        _write_json(Path(args.output), {"schema_version": "vis-arena.agent.v1", **example_agent.info()})
    elif args.command == "models":
        payload = example_agent.models()
        if args.output:
            _write_json(Path(args.output), payload)
        else:
            print(json.dumps(payload, indent=2))
    elif args.command == "generate":
        _run_generate(Path(args.workdir).resolve())
    elif args.command == "evaluate":
        _run_evaluate(Path(args.workdir).resolve())


# ---------------------------------------------------------------------------
# Generate / evaluate dispatch
# ---------------------------------------------------------------------------

def _run_generate(workdir: Path) -> None:
    _require_input(workdir, "task.md")
    _require_input(workdir, "data")
    (workdir / "source").mkdir(parents=True, exist_ok=True)
    (workdir / "dist").mkdir(parents=True, exist_ok=True)

    result = example_agent.generate(workdir) or {}

    if not (workdir / "dist" / "index.html").exists():
        raise SystemExit("Generation failed: dist/index.html was not created")

    task_text = (workdir / "task.md").read_text(encoding="utf-8")
    _write_json(workdir / "generation.json", {
        "schema_version": "vis-arena.generation.v1",
        "task_id": _extract_task_id(task_text),
        "created_at": _now(),
        "notes": result.get("notes") or result.get("summary") or "Generated by template agent.",
    })


def _run_evaluate(workdir: Path) -> None:
    _require_input(workdir, "task.md")
    _require_input(workdir, "data")
    _require_input(workdir, "dist/index.html")

    with _serve_dist(workdir / "dist") as artifact_url:
        result = example_agent.evaluate(workdir, artifact_url) or {}

    task_id = _extract_task_id((workdir / "task.md").read_text(encoding="utf-8"))
    score = float(result.get("score", 0))
    max_score = float(result.get("max_score", 100))
    _write_json(workdir / "evaluation.json", {
        "schema_version": "vis-arena.evaluation.v1",
        "task_id": task_id,
        "score": max(0.0, min(score, max_score)),
        "max_score": max_score,
        "summary": str(result.get("summary", "")),
        "criteria": result.get("criteria", []),
        "browser": result.get("browser", {}),
        "artifacts": result.get("artifacts", {}),
        "metadata": (result.get("metadata") or {}) | {"evaluated_at": _now()},
    })


# ---------------------------------------------------------------------------
# Local HTTP server for the rendered artifact (evaluate only)
# ---------------------------------------------------------------------------

@contextmanager
def _serve_dist(dist_dir: Path) -> Iterator[str]:
    """Serve dist_dir on a random localhost port; yield the index.html URL.

    Binds to 127.0.0.1 only so it is unreachable from outside the sandbox.
    Shuts the server down on context exit.
    """

    class _QuietHandler(http.server.SimpleHTTPRequestHandler):
        def log_message(self, format: str, *args: Any) -> None:  # noqa: A002 — match base signature
            pass

    handler = lambda *a, **kw: _QuietHandler(*a, directory=str(dist_dir), **kw)  # noqa: E731

    class _ReusableTCPServer(socketserver.ThreadingTCPServer):
        allow_reuse_address = True
        daemon_threads = True

    server = _ReusableTCPServer(("127.0.0.1", 0), handler)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        port = server.server_address[1]
        yield f"http://127.0.0.1:{port}/index.html"
    finally:
        server.shutdown()
        server.server_close()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _require_input(workdir: Path, relative: str) -> None:
    if not (workdir / relative).exists():
        raise SystemExit(f"Missing required input in workdir: {relative}")


def _extract_task_id(task_text: str) -> str:
    if task_text.startswith("---"):
        header = task_text.split("---", 2)[1]
        for line in header.splitlines():
            if line.startswith("id:"):
                return line.split(":", 1)[1].strip()
    return "unknown-task"


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def _now() -> str:
    return datetime.now(UTC).isoformat()


if __name__ == "__main__":
    main()
