#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from openai import OpenAI


DEFAULT_MODEL = os.environ.get("VIS_ARENA_OPENAI_MODEL", "gpt-5.5")
MAX_STEPS = int(os.environ.get("VIS_ARENA_AGENT_STEPS", "20"))


GENERATION_PROMPT = """You are a web data visualization agent.
Build a complete browser-ready visualization for the task.
Use the bash tool to inspect data and write files. Put editable source in SOURCE_DIR
and compiled/static browser artifacts in BUILT_DIR. The built artifact must include
index.html and work without a dev server. When done, call finish with a concise JSON
summary."""


EVALUATION_PROMPT = """You are an impartial web visualization evaluator.
Evaluate the submission against the task rubric. Prefer browser evidence by using
the playwright tool. Use source inspection only for behavior that is hard to observe
interactively, such as animation timing or hidden data transforms. When done, call
finish with JSON containing score, max_score, summary, criteria, browser,
source_observations, artifacts, and metadata."""


def main() -> None:
    parser = argparse.ArgumentParser(description="Vis Arena template LLM agent")
    sub = parser.add_subparsers(dest="command", required=True)

    info = sub.add_parser("info")
    info.add_argument("--output", required=True)

    gen = sub.add_parser("generate")
    gen.add_argument("--task", required=True)
    gen.add_argument("--data-dir", required=True)
    gen.add_argument("--output-dir", required=True)

    ev = sub.add_parser("evaluate")
    ev.add_argument("--task", required=True)
    ev.add_argument("--data-dir", required=True)
    ev.add_argument("--source-dir", required=True)
    ev.add_argument("--built-dir", required=True)
    ev.add_argument("--output", required=True)

    args = parser.parse_args()
    if args.command == "info":
        write_json(Path(args.output), info_payload())
    elif args.command == "generate":
        run_generate(args)
    elif args.command == "evaluate":
        run_evaluate(args)


def info_payload() -> dict[str, Any]:
    return {
        "schema_version": "vis-arena.agent.v1",
        "name": "python-openai-template",
        "version": "0.2.0",
        "commands": ["generate", "evaluate"],
        "providers": ["openai"],
        "notes": "Simple OpenAI tool-loop agent with bash and Playwright tools.",
    }


def run_generate(args: argparse.Namespace) -> None:
    output_dir = Path(args.output_dir).resolve()
    source_dir = output_dir / "source"
    built_dir = output_dir / "built"
    source_dir.mkdir(parents=True, exist_ok=True)
    built_dir.mkdir(parents=True, exist_ok=True)

    task_text = Path(args.task).read_text(encoding="utf-8")
    data_dir = Path(args.data_dir).resolve()
    prompt = f"""
TASK_FILE={Path(args.task).resolve()}
DATA_DIR={data_dir}
SOURCE_DIR={source_dir}
BUILT_DIR={built_dir}

Task:
{task_text}
"""
    result = run_agent(GENERATION_PROMPT, prompt, tool_root=output_dir)
    if not (built_dir / "index.html").exists():
        raise SystemExit("Generation failed: built/index.html was not created")
    write_json(
        output_dir / "generation.json",
        {
            "schema_version": "vis-arena.generation.v1",
            "task_id": extract_task_id(task_text),
            "entrypoint": "index.html",
            "source_dir": "source",
            "built_dir": "built",
            "created_at": now(),
            "notes": result.get("summary", "Generated by template LLM agent."),
        },
    )


def run_evaluate(args: argparse.Namespace) -> None:
    output = Path(args.output).resolve()
    report_dir = output.parent
    report_dir.mkdir(parents=True, exist_ok=True)

    task_text = Path(args.task).read_text(encoding="utf-8")
    prompt = f"""
TASK_FILE={Path(args.task).resolve()}
DATA_DIR={Path(args.data_dir).resolve()}
SOURCE_DIR={Path(args.source_dir).resolve()}
BUILT_DIR={Path(args.built_dir).resolve()}
REPORT_DIR={report_dir}
ENTRYPOINT={(Path(args.built_dir).resolve() / "index.html").as_uri()}

Task and rubric:
{task_text}
"""
    result = run_agent(EVALUATION_PROMPT, prompt, tool_root=report_dir)
    report = normalize_evaluation(result, extract_task_id(task_text))
    write_json(output, report)


def run_agent(system_prompt: str, user_prompt: str, tool_root: Path) -> dict[str, Any]:
    client = make_openai_client()
    messages: list[dict[str, Any]] = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt},
    ]
    tools = [
        {
            "type": "function",
            "function": {
                "name": "bash",
                "description": "Run a shell command. Use this to inspect data and create or read files.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "command": {"type": "string"},
                        "cwd": {"type": "string", "description": "Optional working directory."},
                    },
                    "required": ["command"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "playwright",
                "description": "Run a Python Playwright script generated by the agent. The script can inspect pages, screenshots, DOM, console logs, and interactions.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "script": {"type": "string"},
                        "cwd": {"type": "string", "description": "Optional working directory."},
                    },
                    "required": ["script"],
                },
            },
        },
        {
            "type": "function",
            "function": {
                "name": "finish",
                "description": "Return the final JSON result.",
                "parameters": {"type": "object", "properties": {"result": {"type": "object"}}, "required": ["result"]},
            },
        },
    ]

    for _ in range(MAX_STEPS):
        response = client.chat.completions.create(model=DEFAULT_MODEL, messages=messages, tools=tools, tool_choice="auto")
        message = response.choices[0].message
        messages.append(message.model_dump(exclude_none=True))
        if not message.tool_calls:
            messages.append({"role": "user", "content": "Continue using tools, or call finish with the final JSON."})
            continue
        for call in message.tool_calls:
            args = json.loads(call.function.arguments or "{}")
            if call.function.name == "finish":
                return args.get("result") or {}
            if call.function.name == "bash":
                output = run_bash(args["command"], Path(args.get("cwd") or tool_root))
            elif call.function.name == "playwright":
                output = run_playwright(args["script"], Path(args.get("cwd") or tool_root))
            else:
                output = f"Unknown tool: {call.function.name}"
            messages.append({"role": "tool", "tool_call_id": call.id, "content": output[:12000]})
    raise SystemExit(f"Agent exceeded {MAX_STEPS} steps without finishing")


def make_openai_client() -> OpenAI:
    # In cloud evaluation the backend injects VIS_ARENA_API_TOKEN. The agent uses
    # it to ask the arena SDK for a short-lived OpenAI-compatible token/proxy.
    # For local testing, participants should set OPENAI_API_KEY themselves.
    if os.environ.get("VIS_ARENA_API_TOKEN") and not os.environ.get("OPENAI_API_KEY"):
        try:
            from vis_arena_sdk import VisArenaClient

            arena = VisArenaClient(
                base_url=os.environ.get("VIS_ARENA_SERVER_URL", "http://host.docker.internal:8000"),
                token=os.environ["VIS_ARENA_API_TOKEN"],
            )
            token = arena.request_llm_token("openai", DEFAULT_MODEL, purpose="arena-run")
            if token.base_url:
                return OpenAI(api_key=token.access_token, base_url=token.base_url)
            return OpenAI(api_key=token.access_token)
        except Exception as exc:
            raise SystemExit(f"Could not obtain cloud OpenAI token from arena backend: {exc}") from exc
    if not os.environ.get("OPENAI_API_KEY"):
        raise SystemExit("Set OPENAI_API_KEY for local testing, or run inside cloud evaluation with VIS_ARENA_API_TOKEN.")
    return OpenAI()


def run_bash(command: str, cwd: Path) -> str:
    cwd.mkdir(parents=True, exist_ok=True)
    completed = subprocess.run(
        command,
        cwd=str(cwd),
        shell=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        timeout=120,
    )
    return f"$ {command}\nexit={completed.returncode}\n{completed.stdout}"


def run_playwright(script: str, cwd: Path) -> str:
    wrapper = cwd / ".vis_arena_playwright.py"
    wrapper.write_text(script, encoding="utf-8")
    return run_bash(f"{shlex.quote(sys.executable)} {shlex.quote(str(wrapper))}", cwd)


def normalize_evaluation(result: dict[str, Any], task_id: str) -> dict[str, Any]:
    score = float(result.get("score", 0))
    max_score = float(result.get("max_score", 100))
    return {
        "schema_version": "vis-arena.evaluation.v1",
        "task_id": task_id,
        "score": max(0.0, min(score, max_score)),
        "max_score": max_score,
        "summary": str(result.get("summary", "")),
        "criteria": result.get("criteria", []),
        "browser": result.get("browser", {}),
        "source_observations": result.get("source_observations", []),
        "artifacts": result.get("artifacts", {}),
        "metadata": result.get("metadata", {}) | {"evaluated_at": now(), "evaluator": "python-openai-template"},
    }


def extract_task_id(task_text: str) -> str:
    if task_text.startswith("---"):
        header = task_text.split("---", 2)[1]
        for line in header.splitlines():
            if line.startswith("id:"):
                return line.split(":", 1)[1].strip()
    return "unknown-task"


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")


def now() -> str:
    return datetime.now(UTC).isoformat()


if __name__ == "__main__":
    main()
